modernize build
elmotec/massedit pull request #16
Opened 2023-09-10 09:26 UTC by isidroas

Following recent recomendations of setuptools: https://setuptools.pypa.io/en/latest/userguide/quickstart.html

Also, in my system, the script was not generated in the intallation.

2023-09-10 13:03 UTC, elmotec commented
Thanks @isidroas.  That looks good, I feel we need to update the the appveyor.yml [here](https://github.com/elmotec/massedit/blob/0229b40361ed6e752beb81a69f9f78d92c4906d5/.appveyor.yml#L10) and [here](https://github.com/elmotec/massedit/blob/0229b40361ed6e752beb81a69f9f78d92c4906d5/.appveyor.yml#L15) for the PR to pass.  I feel pip is the right choice now so something like `%python% -m pip install .` should do.  Ok to add that to the PR?

2023-09-10 15:50 UTC, isidroas commented
Done, I opted for the first option because it is more minimalist

2023-09-10 19:52 UTC, elmotec commented
Thanks!

2023-09-10 19:56 UTC, elmotec commented
@isidroas, one more thing: it looks like appveyor does not support old version of Python.  I could update the main branch to use python 3.8 and above only per https://devguide.python.org/versions/ but I feel it will trigger conflicts with your branch.  Could you change [.appveyor.yml](https://github.com/elmotec/massedit/blob/0229b40361ed6e752beb81a69f9f78d92c4906d5/.appveyor.yml#L7) to remove Python27, Python34 so the PR passes?

2023-09-10 19:59 UTC, elmotec requested changes
As mentioned [above](https://github.com/elmotec/massedit/pull/16#issuecomment-1712923429), could you remove the references to deprecated versions of Python so the tests pass?

2023-09-10 19:59 UTC, elmotec commented on pyproject.toml
> +    "Programming Language :: Python :: 3.4",
Also remove line 21 and 22 here.  Those versions are no longer supported.  I'll put a separate PR to add 3.10, 3.11. Man, time flies.

2023-09-10 20:08 UTC, elmotec commented on pyproject.toml
> +    "Programming Language :: Python :: 3.4",
And in [.github/workflows/python-app.py](https://github.com/elmotec/massedit/blob/0229b40361ed6e752beb81a69f9f78d92c4906d5/.github/workflows/python-app.yml#L18) as well.

2023-09-10 20:42 UTC, isidroas commented
Changed also _.github/workflows/python-app.py_. I wonder why it is not running, only the appveyor :thinking:

2023-09-11 01:01 UTC, elmotec commented
> Changed also _.github/workflows/python-app.py_. I wonder why it is not running, only the appveyor 🤔

Yeah. Not sure. I'll check that out separately.  Thanks for the PR.

2023-09-11 01:01 UTC, merged